"""
train.py — Training loops for the flow model and the coordinate refiner.

Public API
----------
train_flow(model, train_angles, train_esm2, ...)  -> list[float]
train_refiner(model, train_pids, ...)             -> list[float]
build_training_pair(pid, ...)                     -> (noisy, true, esm2) | None
"""

import os
import random
import pickle as pkl

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from pipeline.nerf import build_backbone
from pipeline.geometry import center_coords, kabsch_align


# ── Flow model training ───────────────────────────────────────────────────────

def train_flow(
    model,
    train_angles: torch.Tensor,
    train_esm2:   torch.Tensor,
    iterations:   int   = 30_000,
    batch_size:   int   = 1024,
    lr:           float = 1e-3,
    print_every:  int   = 2000,
) -> list:
    """Train a ConditionedFlow model with linear flow matching.

    Loss: E_{t, x0, x1, h}[ || v_θ(t, x_t, h) − (x1 − x0) ||² ]

    Parameters
    ----------
    model        : ConditionedFlow
    train_angles : torch.Tensor (N, 2) — φ/ψ angles normalised to [-1, 1]
    train_esm2   : torch.Tensor (N, 320) — per-residue ESM-2 embeddings
    iterations   : int — total gradient steps
    batch_size   : int — residues per step
    lr           : float — initial learning rate (cosine decay to 0)
    print_every  : int — print interval

    Returns
    -------
    loss_history : list[float] — per-step MSE loss
    """
    optimizer    = torch.optim.Adam(model.parameters(), lr=lr)
    scheduler    = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=iterations)
    loss_fn      = nn.MSELoss()
    n_train      = train_angles.shape[0]
    loss_history = []

    model.train()
    for i in range(iterations):
        idx  = torch.randint(0, n_train, (batch_size,))
        x_1  = train_angles[idx]    # (B, 2)
        emb  = train_esm2[idx]      # (B, 320)

        x_0  = torch.randn_like(x_1)
        t    = torch.rand(batch_size, 1)
        x_t  = (1 - t) * x_0 + t * x_1
        dx_t = x_1 - x_0

        optimizer.zero_grad()
        loss = loss_fn(model(t, x_t, emb), dx_t)
        loss.backward()
        optimizer.step()
        scheduler.step()

        loss_history.append(loss.item())
        if (i + 1) % print_every == 0:
            print(f'iter {i+1:6d} | loss {loss.item():.4f} | lr {scheduler.get_last_lr()[0]:.2e}')

    print('Flow training complete.')
    return loss_history


# ── Refiner training data helpers ─────────────────────────────────────────────

def _get_protein_phi_psi(pid: str, L: int, angles_tensor, all_pdb_ids_r) -> np.ndarray:
    """Build (L, 2) φ/ψ array in degrees for *pid*.

    Interior residues (positions 1…L-2) come from the dataset cache.
    Terminal residues default to (-60°, -40°) — canonical α-helix geometry.
    """
    mask      = [p == pid for p in all_pdb_ids_r]
    int_pp    = angles_tensor[torch.tensor(mask)].numpy() * 180.0   # (n_int, 2)
    phi_psi   = np.full((L, 2), [-60., -40.], dtype=np.float32)
    n         = min(len(int_pp), L - 2)
    if n > 0:
        phi_psi[1:1 + n] = int_pp[:n]
    return phi_psi


@torch.no_grad()
def build_training_pair(
    pid:            str,
    backbone_cache: dict,
    esm2_full_cache: dict,
    angles_tensor:  torch.Tensor,
    all_pdb_ids_r:  list,
    noise_std:      float = 25.0,
    flow_model=None,
):
    """Build a (noisy_coords, true_coords, esm2_emb) training triple.

    noisy_coords are generated by:
      - If flow_model is provided: run the flow model on the full protein
      - Otherwise: add Gaussian noise (σ = noise_std°) to the true φ/ψ angles
    Both coordinate sets are centred at their Cα centroid; noisy is then
    Kabsch-aligned to true to correct the arbitrary NeRF frame.

    Parameters
    ----------
    pid              : str — PDB identifier
    backbone_cache   : dict — {pid: {'seq': str, 'coords': (L,4,3)}}
    esm2_full_cache  : dict — {pid: np.ndarray (L, 320)}
    angles_tensor    : torch.Tensor (N_interior, 2) — normalised to [-1,1]
    all_pdb_ids_r    : list[str] — protein ID per interior residue
    noise_std        : float — Gaussian noise std in degrees (ignored if flow_model given)
    flow_model       : ConditionedFlow or None

    Returns
    -------
    (noisy_t, true_t, esm2_t) : tuple of torch.Tensor, or None on failure
      noisy_t : (L, 12) float32 — flattened [N,CA,C,O]×xyz, aligned to true
      true_t  : (L, 12) float32 — centred PDB coordinates
      esm2_t  : (L, 320) float32
    """
    if pid not in backbone_cache or pid not in esm2_full_cache:
        return None

    data     = backbone_cache[pid]
    seq      = data['seq']
    L        = len(seq)
    true_raw = data['coords'].astype(np.float64)   # (L, 4, 3)
    esm2_emb = esm2_full_cache[pid]                # (L, 320) numpy

    if len(true_raw) != L or len(esm2_emb) != L or L < 5 or L > 2048:
        return None

    # Centre true coordinates at their Cα centroid
    true_c, _ = center_coords(true_raw)

    # Generate noisy φ/ψ angles
    if flow_model is not None:
        flow_model.eval()
        emb_t = torch.tensor(esm2_emb, dtype=torch.float32)
        x     = torch.randn(L, 2)
        ts    = torch.linspace(0., 1., 21)
        for i in range(20):
            t_s = ts[i].view(1, 1).expand(L, 1)
            dt  = (ts[i + 1] - ts[i]).float()
            v_s = flow_model(t_s, x, emb_t)
            v_m = flow_model(t_s + dt / 2, x + v_s * dt / 2, emb_t)
            x   = x + dt * v_m
        phi_psi = x.numpy() * 180.0
    else:
        phi_psi = _get_protein_phi_psi(pid, L, angles_tensor, all_pdb_ids_r)
        phi_psi = phi_psi + np.random.randn(L, 2).astype(np.float32) * noise_std

    # NeRF → centre → Kabsch-align to true
    noisy_raw  = build_backbone(seq, phi_psi)
    noisy_c, _ = center_coords(noisy_raw)
    noisy_aln  = kabsch_align(noisy_c, true_c)

    return (
        torch.tensor(noisy_aln.reshape(L, 12), dtype=torch.float32),
        torch.tensor(true_c.reshape(L, 12),    dtype=torch.float32),
        torch.tensor(esm2_emb,                  dtype=torch.float32),
    )


# ── Refiner training loop ─────────────────────────────────────────────────────

def train_refiner(
    model,
    train_pids:      list,
    backbone_cache:  dict,
    esm2_full_cache: dict,
    angles_tensor:   torch.Tensor,
    all_pdb_ids_r:   list,
    epochs:          int   = 30,
    lr:              float = 3e-4,
    noise_std:       float = 25.0,
    print_every:     int   = 5,
    flow_model=None,
    checkpoint_path: str   = 'coord_refiner.pt',
) -> list:
    """Train a CoordRefiner model.

    One protein per gradient step (variable-length sequences — no padding).
    If *flow_model* is provided, its output is used for 20% of proteins;
    the rest use Gaussian-noised true angles.

    Parameters
    ----------
    model            : CoordRefiner
    train_pids       : list[str] — protein IDs for training
    backbone_cache   : dict — {pid: {'seq': str, 'coords': (L,4,3)}}
    esm2_full_cache  : dict — {pid: np.ndarray (L, 320)}
    angles_tensor    : torch.Tensor (N_interior, 2) — normalised to [-1,1]
    all_pdb_ids_r    : list[str] — protein ID per interior residue
    epochs           : int — number of full passes over train_pids
    lr               : float — initial learning rate (cosine decay)
    noise_std        : float — Gaussian angle noise std in degrees
    print_every      : int — epoch print interval
    flow_model       : ConditionedFlow or None — use for realistic noise
    checkpoint_path  : str — where to save the trained model weights

    Returns
    -------
    loss_history : list[float] — per-protein MSE loss
    """
    optimizer    = torch.optim.Adam(model.parameters(), lr=lr)
    scheduler    = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=epochs * len(train_pids)
    )
    loss_history = []

    for epoch in range(epochs):
        model.train()
        epoch_losses  = []
        pids_shuffled = random.sample(train_pids, len(train_pids))

        for pid in pids_shuffled:
            # Use real flow output for ~20% of proteins when available
            use_flow = (flow_model is not None) and (hash(pid) % 5 == 0)
            fm       = flow_model if use_flow else None
            pair     = build_training_pair(
                pid, backbone_cache, esm2_full_cache,
                angles_tensor, all_pdb_ids_r,
                noise_std=noise_std, flow_model=fm,
            )
            if pair is None:
                continue
            noisy_coords, true_coords, esm2_emb = pair

            optimizer.zero_grad()
            refined = model(noisy_coords, esm2_emb)
            loss    = F.mse_loss(refined, true_coords)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()

            epoch_losses.append(loss.item())

        mean_loss = float(np.mean(epoch_losses)) if epoch_losses else float('nan')
        loss_history.extend(epoch_losses)
        if (epoch + 1) % print_every == 0:
            print(f'Epoch {epoch+1:3d}/{epochs} | loss {mean_loss:.5f} | '
                  f'lr {scheduler.get_last_lr()[0]:.2e}')

    print('Refiner training complete.')
    if checkpoint_path:
        torch.save(model.state_dict(), checkpoint_path)
        print(f'Saved → {checkpoint_path}')

    return loss_history
